// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRfxamu1IzqMZKTK_iqsCFcHMBTuci2Rs',
    appId: '1:102856012574:web:bda715272d86be5b0f4f0f',
    messagingSenderId: '102856012574',
    projectId: 'flutter-notifications-6365f',
    authDomain: 'flutter-notifications-6365f.firebaseapp.com',
    storageBucket: 'flutter-notifications-6365f.appspot.com',
    measurementId: 'G-YD347248R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIoiJzYn7K749JntLLb6myOzUqwOyzi4o',
    appId: '1:102856012574:android:8b258adf85614f790f4f0f',
    messagingSenderId: '102856012574',
    projectId: 'flutter-notifications-6365f',
    storageBucket: 'flutter-notifications-6365f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuPfaxhVsddJG1sqhawl8vXh3As43-_js',
    appId: '1:102856012574:ios:f0b41905a0da1a3a0f4f0f',
    messagingSenderId: '102856012574',
    projectId: 'flutter-notifications-6365f',
    storageBucket: 'flutter-notifications-6365f.appspot.com',
    androidClientId: '102856012574-saj91s6eknb6ffsi6bpmdrjcqg1chihl.apps.googleusercontent.com',
    iosClientId: '102856012574-9vbcvalubotn4vranq6njgi4ue5ar0on.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuPfaxhVsddJG1sqhawl8vXh3As43-_js',
    appId: '1:102856012574:ios:f827d11c2362bafe0f4f0f',
    messagingSenderId: '102856012574',
    projectId: 'flutter-notifications-6365f',
    storageBucket: 'flutter-notifications-6365f.appspot.com',
    androidClientId: '102856012574-saj91s6eknb6ffsi6bpmdrjcqg1chihl.apps.googleusercontent.com',
    iosClientId: '102856012574-6i3j5nqrb2fjpvbrr0s019f6n5e5ru8d.apps.googleusercontent.com',
    iosBundleId: 'com.example.pushApp.RunnerTests',
  );
}
